# Generated by Django 3.0.1 on 2020-05-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, verbose_name='邀请码')),
                ('usedBy', models.CharField(default='', max_length=1000, verbose_name='被谁使用')),
                ('addBy', models.CharField(default='', max_length=1000, verbose_name='由谁加入')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('usedTime', models.CharField(max_length=1000, verbose_name='使用时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=13, verbose_name='学号')),
                ('stu_pass', models.CharField(max_length=64, verbose_name='密码')),
                ('SCKey', models.CharField(default='', max_length=128, verbose_name='SCKey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('content', models.CharField(default=True, max_length=512, verbose_name='打卡返回信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Record', to='scujkbapp.UserProfile')),
            ],
            options={
                'verbose_name': '打卡记录',
            },
        ),
    ]
