# Generated by Django 3.0.1 on 2020-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scujkbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vaild',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='record',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(default='', max_length=512, verbose_name='返回信息'),
        ),
    ]
