# Generated by Django 3.0.1 on 2021-01-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scujkbapp', '0002_auto_20200529_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wx_uid',
            field=models.CharField(default='', max_length=128, verbose_name='微信UID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Record', to='scujkbapp.UserProfile'),
        ),
    ]
