# Generated by Django 3.0.1 on 2021-01-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scujkbapp', '0003_auto_20210108_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vaild',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
    ]
